name: Deploy to AWS Fargate

on:
  push:
    branches:
      - main  # Runs on push to main branch

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1  # Change if your AWS region is different

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin 123456789012.dkr.ecr.ca-central-1.amazonaws.com

      - name: Build, tag, and push Docker image
        run: |
          docker build -t task-manager-app .
          docker tag task-manager-app:latest 796973517423.dkr.ecr.ca-central-1.amazonaws.com/task-manager-app:latest
          docker push 796973517423.dkr.ecr.ca-central-1.amazonaws.com/task-manager-app:latest

      - name: Update ECS Service
        run: |
          aws ecs update-service --cluster task-manager-cluster --service task-manager-service --force-new-deployment
